### ISSUE TITLE
Frame Rate data not found on page refresh

### ISSUE THREAD

**Issue by AtulUjjwal** [axemclion/perfjankie#28] opened 2015-12-23 10:27 UTC
Hi,
When i am trying to perform page refresh under actions using "browser.refresh()", the perf graph for frame rate trend is not plotted.
Regards,
Atul

**Comment by axemclion** [comment] 2015-12-23 18:49
In such cases, there is a chance that the benchmark metric did not fire. What page are you trying to test ?

**Comment by AtulUjjwal** [comment] 2015-12-24 05:45
I have tried for my local page but am not getting values for "https://angularjs.org/" , and "http://google.com" too.

**Comment by axemclion** [comment] 2015-12-24 18:09
@AtulUjjwal In hte default test, you would need to run it against a page that scrolls. Can you run  [browser-perf](http://npmjs.org/package/browser-perf) directly on angular ? You should get framerates there. 

If you still do not get the metrics, can you run it again with `export DEBUG=*` and paste the logs here ?

**Comment by AtulUjjwal** [comment] 2015-12-29 09:13
Getting error as :
c:\Jenkins\workspace\test_suite\node_modules\perfjankie\node_modules\q\q.js:155
                throw e;
                ^
Error: [log("performance")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Java heap space
 Use --force to continue.

The error comes after running the tests, can you please help regarding this ?

**Comment by axemclion** [comment] 2015-12-29 16:48
@AtulUjjwal Looks like you would have to run selenium with a larger heap. Can you set the JAVA opts while running selenium to a larger heap space ? Alternatively, you could simply run chromedriver and that should also work well.

**Comment by AtulUjjwal** [comment] 2015-12-30 04:10
Can we increase the heap size from Perf Jankie args ?

**Comment by axemclion** [comment] 2015-12-30 05:16
Unfortunately, the heap size is an issue with Java/Selenium. How is your selenium server run ? Can you run it with just chromedriver ? 


Perfjankie cannot really do anything about the heap size of a Java JVM.

**Comment by AtulUjjwal** [comment] 2015-12-30 16:21
I tried running with chromedriver but the issue still happens.
The main issue is that my action command queue is a bit long in order to run synchronously.
If I divide my action list into "prescript" and "actions" , it works fine, but the perf data for "prescript" is not included. 
Is there any other way to call synchronous commands other than chaining in Perf Jankie ?

**Comment by axemclion** [comment] 2015-12-30 16:31
One way to do that would be to have a function that runs your sequence of commands, and then pass it all at once to the page. However, that is not the problem - the problem is that the logs become way too big for chromedriver to handle. 
Another way could be to disable some of the metrics and thus make the logs smaller. Is there a specific metric you are looking for ? If you are only looking for frames per sec, you could just ask for the "TimelineMetrics".

**Comment by AtulUjjwal** [comment] 2015-12-31 01:41
ok, how to provide "TimelineMetrics" to perf-jankie ?

**Comment by AtulUjjwal** [comment] 2015-12-31 03:36
Updating with only "TimelineMetrics" resolves heap error, thanks.
But i cannot scroll the web page using "browser.scroll(offsetx,offsety). It is giving the error "Selenium error: Underlying driver does not implement advanced user interactions yet.".
Is there any other way ?

**Comment by AtulUjjwal** [comment] 2015-12-31 04:42
Also, Is there any way to customize the Perf data graph page on the couch server.
I mean If i want to remove the FPS plot view from home page , how can i do that ?

**Comment by axemclion** [comment] 2015-12-31 05:15
What version of selenium/chromedriver are you using? At the moment, perfjankie does not really have a way to customize the dashboard. it is simply an Angular app, so you should be able to fork it and change it to suit your needs.

**Comment by axemclion** [comment] 2015-12-31 05:15
Closing this issue, if you have more quesitons, please do respond to this thread.

**Closed by axemclion** 2015-12-31 05:15 UTC
Labels: question

**Comment by AtulUjjwal** [comment] 2015-12-31 05:25
Sure,
I am using selenium-server-standalone-2.46.0.

**Comment by axemclion** [comment] 2015-12-31 05:37
If you are using chrome, I would recommend using window.chrome.gpuBenchmarking.smoothScrollBy() instead - this mimics the user scroll much better.

**Comment by AtulUjjwal** [comment] 2015-12-31 05:44
I have to develop the functionalities cross - platform , will this also work on linux ?

**Comment by axemclion** [comment] 2015-12-31 06:12
@AtulUjjwal It should work across Chrome on linux too.
