### ISSUE TITLE
Cannot run a tool to profiling on Android / Nexus 7 - results are not saved in couchdb

### ISSUE THREAD

**Issue by hinok** [axemclion/perfjankie#21] opened 2015-02-02 02:36 UTC
Hey,
I was able to run browser-perf and connect to android device and get results. Awesome.

When I use perfjankie, results are not saved in couchdb. While page is scrolled, Chrome shows a message on android device which can be translated as:
```
Cannot run a tool to profiling
```

When scrolling is finished, nothing happens.
I'm not sure but from my perspective perfjankie waits for a response or an action.
After tens seconds chrome closes on android device and logs are returned to terminal, the bottom of logs:

```
[27.973][INFO]: RESPONSE GetSessionCapabilities {
   "acceptSslCerts": true,
   "applicationCacheEnabled": false,
   "browserConnectionEnabled": false,
   "browserName": "chrome",
   "chrome": {

   },
   "cssSelectorsEnabled": true,
   "databaseEnabled": false,
   "handlesAlerts": true,
   "javascriptEnabled": true,
   "locationContextEnabled": true,
   "mobileEmulationEnabled": false,
   "nativeEvents": true,
   "platform": "ANDROID",
   "rotatable": false,
   "takesHeapSnapshot": true,
   "takesScreenshot": true,
   "version": "40.0.2214.89",
   "webStorageEnabled": true
}
[148.913][INFO]: COMMAND Quit {

}
[148.913][DEBUG]: Sending adb command: host:transport:015d24a42d442004|shell:am force-stop com.android.chrome
[150.003][DEBUG]: Received adb response: 
[150.003][INFO]: RESPONSE Quit
[150.003][DEBUG]: Log type 'driver' lost 0 entries on destruction
[150.003][DEBUG]: Log type 'performance' lost 0 entries on destruction
[150.003][DEBUG]: Log type 'browser' lost 2 entries on destruction
```

Full logs: https://www.dropbox.com/s/9sec5zwxn5agkdo/perfjankie-chromedriver-logs-dump.txt?dl=0 (Attention, 2.6mb)

- chromeDriver 2.13.307650
- perfjankie 1.1.2
- Nexus 7, Android 5.0.2 + Chrome 40.0.2214.89

Thanks.

**Comment by axemclion** [comment] 2015-02-03 00:00
This sounds more like a browser-perf issue. I think we would need to fix this in browser-perf first, and see if this bug can be reproduced on perfjankie. Looking into the browser-perf bug now.

**Comment by axemclion** [comment] 2015-04-02 04:16
Closing this issue since browser-perf issue is closed.

**Closed by axemclion** 2015-04-02 04:16 UTC
