### ISSUE TITLE
Frame rate graph not working

### ISSUE THREAD

**Issue by arschmitz** [axemclion/perfjankie#16] opened 2015-01-22 14:57 UTC
Have been working with this for some jQuery projects and the frame rate graph does not seem to be working. http://104.236.81.132:5984/css-perf/_design/site/index.html#/page-select

**Comment by axemclion** [comment] 2015-01-22 21:08
This looks like a regression. There was no frames-per-sec metric, it was dynamically calculated from mean_frame_time. I am now working on moving this to the latest version of browser-perf that emits a frame_rate in addition to mean_frame_time. That should fix this issue.

**Comment by axemclion** [comment] 2015-03-01 03:38
@arschmitz I fixed this in this (change](https://github.com/axemclion/perfjankie/commit/aee5dd1c8295f7bb422dae6f036fd76c1023f3dd).

You may need to migrate your older data, and this [documentation](https://github.com/axemclion/perfjankie#migrating-data-from-older-versions) should help.

**Closed by axemclion** 2015-03-01 03:38 UTC
